### ISSUE TITLE
행정구역 목록 조회 API 구현

### ISSUE THREAD

**Issue by Wo-ogie** [Ajou-Hertz/hertz-backend#38]
## 🔥 Issue
행정구역 목록 조회 API 구현

## ✅ TODO
- [ ] 행정구역 관련 entity 구현
  - [ ] 시/도 entity 구현
  - [ ] 시/군/구 entity 구현
  - [ ] 읍/면/동 entity 구현
- [ ] 행정구역 목록 조회 API 구현
  - [ ] 시/도 목록 조회 API 구현
  - [ ] 시/군/구 목록 조회 API 구현
  - [ ] 읍/면/동 목록 조회 API 구현
