### ISSUE TITLE
악기 관련 entity 구현

### ISSUE THREAD

**Issue by Wo-ogie** [Ajou-Hertz/hertz-backend#46]
## 🔥 Issue
악기 관련 entity 구현

## ✅ TODO
- [x] 악기 entity 구현
- [x] 악기 매물 사진 entity 구현
- [x] 악기 hashtag entity 구현
