### ISSUE TITLE
종류별 악기 목록 조회 API 구현

### ISSUE THREAD

**Issue by Wo-ogie** [Ajou-Hertz/hertz-backend#67]
## 🔥 Issue
종류별 악기 목록 조회 API 구현

## ✅ TODO
- [x] 일렉 기타 목록 조회 API 구현
- [x] 베이스 기타 목록 조회 API 구현
- [x] 어쿠스틱&클래식 기타 목록 조회 API 구현
- [x] 이펙터 목록 조회 API 구현
- [x] 앰프 목록 조회 API 구현
- [x] 음향 장비 목록 조회 API 구현
