### ISSUE TITLE
회원 탈퇴 API 구현

### ISSUE THREAD

**Issue by Wo-ogie** [Ajou-Hertz/hertz-backend#70]
## 🔥 Issue
회원 탈퇴 시 연관된 resource의 처리 여부에 대해 정책 논의 필요. (Soft delete 고려, 연관된 resource 전체 삭제 등)
정책 논의 후 개발 진행.

## ✅ TODO
- [x] 회원 탈퇴 정책 논의 (with. 기획팀)
- [x] 회원 탈퇴 API 구현
  - [ ] 회원 탈퇴 시, 7일간 탈퇴 이력(전화번호)을 남기도록 구현
