### ISSUE TITLE
악기 종류별 목록 조회 API - 종류별 필터 조건 추가

### ISSUE THREAD

**Issue by Wo-ogie** [Ajou-Hertz/hertz-backend#75]
## 🔥 Issue
#67 에서 진행하지 않았던 악기 종류별 필터 조건을 추가한다.

## ✅ TODO
- [ ] 일렉 기타 필터 조건 추가
- [ ] 베이스 기타 필터 조건 추가
- [ ] 어쿠스틱&클래식 기타 필터 조건 추가
- [ ] 이펙터 필터 조건 추가
- [ ] 앰프 필터 조건 추가
- [ ] 음향 장비 필터 조건 추가
